/*
Created: 21/12/2022
Modified: 15/02/2023
Model: Oracle 11g Release 2
Database: Oracle 11g Release 2
*/


-- Create tables section -------------------------------------------------

-- Table USUARIO

CREATE TABLE "USUARIO"(
  "USUARIO_ID" Number(5,0) NOT NULL,
  "NOMBRE_USUARIO" Varchar2(30 ) NOT NULL,
  "APELLIDO1" Varchar2(30 ) NOT NULL,
  "APELLIDO2" Varchar2(30 ),
  "CORREO" Varchar2(50 ) NOT NULL,
  "CONTRASENA" Char(64 ) NOT NULL,
  "ICONO_USUARIO" Varchar2(2000 ),
  "ALIAS" Varchar2(30 ) NOT NULL,
  CONSTRAINT "CC_CORREO" CHECK (correo like '%@%.%')
)
/

-- Add keys for table USUARIO

ALTER TABLE "USUARIO" ADD CONSTRAINT "Key1" PRIMARY KEY ("USUARIO_ID")
;

ALTER TABLE "USUARIO" ADD CONSTRAINT "CORREO" UNIQUE ("CORREO")
;

ALTER TABLE "USUARIO" ADD CONSTRAINT "ALIAS" UNIQUE ("ALIAS")
;
ALTER TABLE "USUARIO" ADD CONSTRAINT CC_ALIAS CHECK (LENGTH(ALIAS) > 1)
;

-- Table LISTA

CREATE TABLE "LISTA"(
  "LISTA_ID" Number(5,0) NOT NULL,
  "NOMBRE_LISTA" Varchar2(30 ) NOT NULL,
  "ICONO_LISTA" Varchar2(2000 ),
  "FECHA_CREACION" Date DEFAULT SYSDATE NOT NULL,
  "USUARIO_ID" Number(5,0) NOT NULL
)
/

-- Create indexes for table LISTA

CREATE INDEX "IX_Relationship1" ON "LISTA" ("USUARIO_ID")
;

-- Add keys for table LISTA

ALTER TABLE "LISTA" ADD CONSTRAINT "Key2" PRIMARY KEY ("LISTA_ID")
;

ALTER TABLE "LISTA" ADD CONSTRAINT "AK_NOMBRE_USUARIO" UNIQUE ("USUARIO_ID","NOMBRE_LISTA")
;

-- Table CANCION

CREATE TABLE "CANCION"(
  "CANCION_ID" Number(5,0) NOT NULL,
  "NOMBRE_CANCION" Varchar2(30 ) NOT NULL,
  "DURACION" Number(4,2) NOT NULL,
  "ARTISTA" Varchar2(30 )
)
/

-- Add keys for table CANCION

ALTER TABLE "CANCION" ADD CONSTRAINT "Key3" PRIMARY KEY ("CANCION_ID")
;

-- Table LISTA_CANCION

CREATE TABLE "LISTA_CANCION"(
  "LISTA_ID" Number(5,0) NOT NULL,
  "CANCION_ID" Number(5,0) NOT NULL
)
/

-- Add keys for table LISTA_CANCION

ALTER TABLE "LISTA_CANCION" ADD CONSTRAINT "Key4" PRIMARY KEY ("LISTA_ID","CANCION_ID")
;

-- Table FAVORITO

CREATE TABLE "FAVORITO"(
  "USUARIO_ID" Number(5,0) NOT NULL,
  "CANCION_ID" Number(5,0) NOT NULL
)
/

-- Add keys for table FAVORITO

ALTER TABLE "FAVORITO" ADD CONSTRAINT "Key5" PRIMARY KEY ("CANCION_ID","USUARIO_ID")
;


-- Create foreign keys (relationships) section ------------------------------------------------- 

ALTER TABLE "LISTA" ADD CONSTRAINT "Relationship1" FOREIGN KEY ("USUARIO_ID") REFERENCES "USUARIO" ("USUARIO_ID")
;


ALTER TABLE "LISTA_CANCION" ADD CONSTRAINT "Relationship2" FOREIGN KEY ("LISTA_ID") REFERENCES "LISTA" ("LISTA_ID")
;


ALTER TABLE "LISTA_CANCION" ADD CONSTRAINT "Relationship3" FOREIGN KEY ("CANCION_ID") REFERENCES "CANCION" ("CANCION_ID")
;


ALTER TABLE "FAVORITO" ADD CONSTRAINT "Relationship4" FOREIGN KEY ("CANCION_ID") REFERENCES "CANCION" ("CANCION_ID")
;


ALTER TABLE "FAVORITO" ADD CONSTRAINT "Relationship5" FOREIGN KEY ("USUARIO_ID") REFERENCES "USUARIO" ("USUARIO_ID")
;
