-- ALTER TABLE xxx DISABLE CONSTRAINT xxx; 

-- ALTER TABLE LISTA ADD CONSTRAINT CC_NombreLista CHECK (LENGTH(NOMBRE) >= 1);

-- alter table cancion modify DURACION number(4,2);
    
-- Inserts CANCION -------------------   
INSERT INTO CANCION (CANCION_ID,NOMBRE_CANCION,DURACION,ARTISTA)
VALUES (S_CANCION.nextval,'Heat Waves',3,'Glass Animals');

INSERT INTO CANCION (CANCION_ID,NOMBRE_CANCION,DURACION,ARTISTA)
VALUES (S_CANCION.nextval,'Post Malone',2.34,null);

INSERT INTO CANCION (CANCION_ID,NOMBRE_CANCION,DURACION,ARTISTA)
VALUES (S_CANCION.nextval,'Night y Day',5.11,'Mr Groove');

INSERT INTO CANCION (CANCION_ID,NOMBRE_CANCION,DURACION,ARTISTA)
VALUES (S_CANCION.nextval,'In da Getto',2.11,'J Balvin , Skrillex');

INSERT INTO CANCION (CANCION_ID,NOMBRE_CANCION,DURACION,ARTISTA)
VALUES (S_CANCION.nextval,'No Way',3.03,'Dongurizu');

INSERT INTO CANCION (CANCION_ID,NOMBRE_CANCION,DURACION,ARTISTA)
VALUES (S_CANCION.nextval,'You Know How We Do It',3.52,'Ice Cube');

-- -----------------------------------

-- Inserts USUARIO -------------------  

INSERT INTO USUARIO (USUARIO_ID,NOMBRE_USUARIO,APELLIDO1,APELLIDO2,CORREO,CONTRASENA,ICONO_USUARIO,ALIAS)
VALUES (S_USUARIO.nextval,'Nelson','Macedo','Sanchez','12345@gmail.com','123456',null,'Nelfire');

INSERT INTO USUARIO (USUARIO_ID,NOMBRE_USUARIO,APELLIDO1,APELLIDO2,CORREO,CONTRASENA,ICONO_USUARIO,ALIAS)
VALUES (S_USUARIO.nextval,'Roberto','Irusta',null,'1@gmail.com','1111111',null,'Robertito');

INSERT INTO USUARIO (USUARIO_ID,NOMBRE_USUARIO,APELLIDO1,APELLIDO2,CORREO,CONTRASENA,ICONO_USUARIO,ALIAS)
VALUES (S_USUARIO.nextval,'Imanol','Callejo',null,'2@gmail.com',22222222,null,'Ima');

INSERT INTO USUARIO (USUARIO_ID,NOMBRE_USUARIO,APELLIDO1,APELLIDO2,CORREO,CONTRASENA,ICONO_USUARIO,ALIAS)
VALUES (S_USUARIO.nextval,'Luis','Fernandez',null,'3@gmail.com',3333333333,null,'_Destroyer_');

INSERT INTO USUARIO (USUARIO_ID,NOMBRE_USUARIO,APELLIDO1,APELLIDO2,CORREO,CONTRASENA,ICONO_USUARIO,ALIAS)
VALUES (S_USUARIO.nextval,'Daniel','Diez',null,'4@gmail.com',4444444444,null,'DANIN');

-- Inserts LISTA ---------------------------------------------------

INSERT INTO LISTA (LISTA_ID,NOMBRE_LISTA,ICONO_LISTA,FECHA_CREACION,USUARIO_ID)
VALUES (S_LISTA.nextval,'POP',null,default,1);

INSERT INTO LISTA (LISTA_ID,NOMBRE_LISTA,ICONO_LISTA,FECHA_CREACION,USUARIO_ID)
VALUES (S_LISTA.nextval,'ROCK',null,default,1);

INSERT INTO LISTA (LISTA_ID,NOMBRE_LISTA,ICONO_LISTA,FECHA_CREACION,USUARIO_ID)
VALUES (S_LISTA.nextval,'Heavy',null,default,1);

INSERT INTO LISTA (LISTA_ID,NOMBRE_LISTA,ICONO_LISTA,FECHA_CREACION,USUARIO_ID)
VALUES (S_LISTA.nextval,'Mega',null,default,1);

-- Inserts Favorito -------------------------------------------------------------------

INSERT INTO FAVORITO (USUARIO_ID,CANCION_ID)
VALUES (1,3);

-- Inserts Favorito -------------------------------------------------------------------

INSERT INTO LISTA_CANCION (LISTA_ID,CANCION_ID)
VALUES (1,5);

-- ----------------------------------------------------------------
commit;