
-- Creacion Secuencias

CREATE SEQUENCE  "PLAYER"."S_CANCION"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE SEQUENCE  "PLAYER"."S_LISTA"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE SEQUENCE  "PLAYER"."S_USUARIO"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;



--Borrado de Secuencias

--select * from all_sequences;

--drop sequence S_USUARIO;
--drop sequence S_CANCION;
--drop sequence S_LISTA;